/**
 * Derives the converter's three inputs from `.design-sync/config.json`, so none
 * can drift from the component list.
 *
 *   .design-sync/generated/ds-entry.tsx  the bundle entry
 *   .design-sync/generated/tokens.css    theme.ts as CSS custom properties
 *   dist/types/ds-props.d.ts             a <Name>Props alias per component
 *
 * Run from the repository root: `npx tsx .design-sync/gen.ts`
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative } from 'node:path';
import { darkTheme, lightTheme } from '../src/constants/theme';

const config = JSON.parse(readFileSync('.design-sync/config.json', 'utf8'));
const components: Record<string, string> = config.componentSrcMap;
const names = Object.keys(components).sort();

const GENERATED = '.design-sync/generated';
const TYPES = 'dist/types/ds-props.d.ts';
mkdirSync(GENERATED, { recursive: true });
mkdirSync(dirname(TYPES), { recursive: true });

const moduleOf = (from: string, src: string) =>
  relative(dirname(from), src).replace(/\.tsx?$/, '').replace(/^(?!\.)/, './');

// A component that reads a store and takes no props can only show the store's
// initial value, so the stores ride along and a preview can seed them.
const STORES = ['settingsStore', 'recitationStore', 'reciterStore', 'readingStore'];

writeFileSync(
  `${GENERATED}/ds-entry.tsx`,
  '// Generated by .design-sync/gen.ts - do not edit.\n' +
    "import '../shims/process-polyfill';\n" +
    names.map((n) => `export { ${n} } from '${moduleOf(GENERATED + '/x', components[n])}';\n`).join('') +
    STORES.map((s) => `export * from '${moduleOf(GENERATED + '/x', `src/stores/${s}.ts`)}';\n`).join(''),
);

// The components declare a local `interface Props`, so these aliases give the
// converter the `<Name>Props` it looks for.
writeFileSync(
  TYPES,
  '// Generated by .design-sync/gen.ts - do not edit.\n' +
    "import type { ComponentProps } from 'react';\n" +
    names
      .map(
        (n) =>
          `export type ${n}Props = ComponentProps<typeof import('${moduleOf(TYPES, components[n])}').${n}>;\n`,
      )
      .join(''),
);

const px = (n: number) => `${n}px`;
const lines = (obj: Record<string, unknown>, prefix: string, format: (v: never) => string) =>
  Object.entries(obj).map(([k, v]) => `  --${prefix}-${k}: ${format(v as never)};`);

const scale = Object.entries(lightTheme.typeScale).flatMap(([k, v]) => [
  `  --text-${k}-size: ${px(v.size)};`,
  `  --text-${k}-line-height: ${v.lineHeight};`,
]);

writeFileSync(
  `${GENERATED}/tokens.css`,
  [
    '/* Generated by .design-sync/gen.ts from src/constants/theme.ts - do not edit. */',
    ':root {',
    ...lines(lightTheme.semantic, 'color', String),
    ...lines(lightTheme.spacing, 'space', px),
    ...lines(lightTheme.radii, 'radius', px),
    ...lines(lightTheme.gutter, 'gutter', px),
    ...scale,
    ...Object.entries(lightTheme.fonts).map(([k, v]) => `  --font-${k}: '${v}';`),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    '  :root {',
    ...lines(darkTheme.semantic, 'color', String).map((l) => '  ' + l),
    '  }',
    '}',
    '',
  ].join('\n'),
);

console.log(`generated entry + types for ${names.length} components, and tokens.css`);
