export const TOTAL_SURAHS = 114;
export const TOTAL_AYAHS = 6236;
export const TOTAL_JUZ = 30;

export interface SurahMetadata {
  number: number;
  nameArabic: string;
  nameEnglish: string;
  ayahCount: number;
  revelationType: 'Makki' | 'Madani';
}

/** Static metadata for all 114 surahs. Used for search fallback and validation. */
export const SURAH_METADATA: SurahMetadata[] = [
  { number: 1, nameArabic: 'الفاتحة', nameEnglish: 'Al-Fatiha', ayahCount: 7, revelationType: 'Makki' },
  { number: 2, nameArabic: 'البقرة', nameEnglish: 'Al-Baqarah', ayahCount: 286, revelationType: 'Madani' },
  { number: 3, nameArabic: 'آل عمران', nameEnglish: 'Ali Imran', ayahCount: 200, revelationType: 'Madani' },
  { number: 4, nameArabic: 'النساء', nameEnglish: 'An-Nisa', ayahCount: 176, revelationType: 'Madani' },
  { number: 5, nameArabic: 'المائدة', nameEnglish: 'Al-Maidah', ayahCount: 120, revelationType: 'Madani' },
  { number: 6, nameArabic: 'الأنعام', nameEnglish: 'Al-Anam', ayahCount: 165, revelationType: 'Makki' },
  { number: 7, nameArabic: 'الأعراف', nameEnglish: 'Al-Araf', ayahCount: 206, revelationType: 'Makki' },
  { number: 8, nameArabic: 'الأنفال', nameEnglish: 'Al-Anfal', ayahCount: 75, revelationType: 'Madani' },
  { number: 9, nameArabic: 'التوبة', nameEnglish: 'At-Tawbah', ayahCount: 129, revelationType: 'Madani' },
  { number: 10, nameArabic: 'يونس', nameEnglish: 'Yunus', ayahCount: 109, revelationType: 'Makki' },
  { number: 11, nameArabic: 'هود', nameEnglish: 'Hud', ayahCount: 123, revelationType: 'Makki' },
  { number: 12, nameArabic: 'يوسف', nameEnglish: 'Yusuf', ayahCount: 111, revelationType: 'Makki' },
  { number: 13, nameArabic: 'الرعد', nameEnglish: 'Ar-Rad', ayahCount: 43, revelationType: 'Madani' },
  { number: 14, nameArabic: 'إبراهيم', nameEnglish: 'Ibrahim', ayahCount: 52, revelationType: 'Makki' },
  { number: 15, nameArabic: 'الحجر', nameEnglish: 'Al-Hijr', ayahCount: 99, revelationType: 'Makki' },
  { number: 16, nameArabic: 'النحل', nameEnglish: 'An-Nahl', ayahCount: 128, revelationType: 'Makki' },
  { number: 17, nameArabic: 'الإسراء', nameEnglish: 'Al-Isra', ayahCount: 111, revelationType: 'Makki' },
  { number: 18, nameArabic: 'الكهف', nameEnglish: 'Al-Kahf', ayahCount: 110, revelationType: 'Makki' },
  { number: 19, nameArabic: 'مريم', nameEnglish: 'Maryam', ayahCount: 98, revelationType: 'Makki' },
  { number: 20, nameArabic: 'طه', nameEnglish: 'Ta-Ha', ayahCount: 135, revelationType: 'Makki' },
  { number: 21, nameArabic: 'الأنبياء', nameEnglish: 'Al-Anbiya', ayahCount: 112, revelationType: 'Makki' },
  { number: 22, nameArabic: 'الحج', nameEnglish: 'Al-Hajj', ayahCount: 78, revelationType: 'Madani' },
  { number: 23, nameArabic: 'المؤمنون', nameEnglish: 'Al-Muminun', ayahCount: 118, revelationType: 'Makki' },
  { number: 24, nameArabic: 'النور', nameEnglish: 'An-Nur', ayahCount: 64, revelationType: 'Madani' },
  { number: 25, nameArabic: 'الفرقان', nameEnglish: 'Al-Furqan', ayahCount: 77, revelationType: 'Makki' },
  { number: 26, nameArabic: 'الشعراء', nameEnglish: 'Ash-Shuara', ayahCount: 227, revelationType: 'Makki' },
  { number: 27, nameArabic: 'النمل', nameEnglish: 'An-Naml', ayahCount: 93, revelationType: 'Makki' },
  { number: 28, nameArabic: 'القصص', nameEnglish: 'Al-Qasas', ayahCount: 88, revelationType: 'Makki' },
  { number: 29, nameArabic: 'العنكبوت', nameEnglish: 'Al-Ankabut', ayahCount: 69, revelationType: 'Makki' },
  { number: 30, nameArabic: 'الروم', nameEnglish: 'Ar-Rum', ayahCount: 60, revelationType: 'Makki' },
  { number: 31, nameArabic: 'لقمان', nameEnglish: 'Luqman', ayahCount: 34, revelationType: 'Makki' },
  { number: 32, nameArabic: 'السجدة', nameEnglish: 'As-Sajdah', ayahCount: 30, revelationType: 'Makki' },
  { number: 33, nameArabic: 'الأحزاب', nameEnglish: 'Al-Ahzab', ayahCount: 73, revelationType: 'Madani' },
  { number: 34, nameArabic: 'سبأ', nameEnglish: 'Saba', ayahCount: 54, revelationType: 'Makki' },
  { number: 35, nameArabic: 'فاطر', nameEnglish: 'Fatir', ayahCount: 45, revelationType: 'Makki' },
  { number: 36, nameArabic: 'يس', nameEnglish: 'Ya-Sin', ayahCount: 83, revelationType: 'Makki' },
  { number: 37, nameArabic: 'الصافات', nameEnglish: 'As-Saffat', ayahCount: 182, revelationType: 'Makki' },
  { number: 38, nameArabic: 'ص', nameEnglish: 'Sad', ayahCount: 88, revelationType: 'Makki' },
  { number: 39, nameArabic: 'الزمر', nameEnglish: 'Az-Zumar', ayahCount: 75, revelationType: 'Makki' },
  { number: 40, nameArabic: 'غافر', nameEnglish: 'Ghafir', ayahCount: 85, revelationType: 'Makki' },
  { number: 41, nameArabic: 'فصلت', nameEnglish: 'Fussilat', ayahCount: 54, revelationType: 'Makki' },
  { number: 42, nameArabic: 'الشورى', nameEnglish: 'Ash-Shura', ayahCount: 53, revelationType: 'Makki' },
  { number: 43, nameArabic: 'الزخرف', nameEnglish: 'Az-Zukhruf', ayahCount: 89, revelationType: 'Makki' },
  { number: 44, nameArabic: 'الدخان', nameEnglish: 'Ad-Dukhan', ayahCount: 59, revelationType: 'Makki' },
  { number: 45, nameArabic: 'الجاثية', nameEnglish: 'Al-Jathiyah', ayahCount: 37, revelationType: 'Makki' },
  { number: 46, nameArabic: 'الأحقاف', nameEnglish: 'Al-Ahqaf', ayahCount: 35, revelationType: 'Makki' },
  { number: 47, nameArabic: 'محمد', nameEnglish: 'Muhammad', ayahCount: 38, revelationType: 'Madani' },
  { number: 48, nameArabic: 'الفتح', nameEnglish: 'Al-Fath', ayahCount: 29, revelationType: 'Madani' },
  { number: 49, nameArabic: 'الحجرات', nameEnglish: 'Al-Hujurat', ayahCount: 18, revelationType: 'Madani' },
  { number: 50, nameArabic: 'ق', nameEnglish: 'Qaf', ayahCount: 45, revelationType: 'Makki' },
  { number: 51, nameArabic: 'الذاريات', nameEnglish: 'Adh-Dhariyat', ayahCount: 60, revelationType: 'Makki' },
  { number: 52, nameArabic: 'الطور', nameEnglish: 'At-Tur', ayahCount: 49, revelationType: 'Makki' },
  { number: 53, nameArabic: 'النجم', nameEnglish: 'An-Najm', ayahCount: 62, revelationType: 'Makki' },
  { number: 54, nameArabic: 'القمر', nameEnglish: 'Al-Qamar', ayahCount: 55, revelationType: 'Makki' },
  { number: 55, nameArabic: 'الرحمن', nameEnglish: 'Ar-Rahman', ayahCount: 78, revelationType: 'Madani' },
  { number: 56, nameArabic: 'الواقعة', nameEnglish: 'Al-Waqiah', ayahCount: 96, revelationType: 'Makki' },
  { number: 57, nameArabic: 'الحديد', nameEnglish: 'Al-Hadid', ayahCount: 29, revelationType: 'Madani' },
  { number: 58, nameArabic: 'المجادلة', nameEnglish: 'Al-Mujadilah', ayahCount: 22, revelationType: 'Madani' },
  { number: 59, nameArabic: 'الحشر', nameEnglish: 'Al-Hashr', ayahCount: 24, revelationType: 'Madani' },
  { number: 60, nameArabic: 'الممتحنة', nameEnglish: 'Al-Mumtahanah', ayahCount: 13, revelationType: 'Madani' },
  { number: 61, nameArabic: 'الصف', nameEnglish: 'As-Saf', ayahCount: 14, revelationType: 'Madani' },
  { number: 62, nameArabic: 'الجمعة', nameEnglish: 'Al-Jumuah', ayahCount: 11, revelationType: 'Madani' },
  { number: 63, nameArabic: 'المنافقون', nameEnglish: 'Al-Munafiqun', ayahCount: 11, revelationType: 'Madani' },
  { number: 64, nameArabic: 'التغابن', nameEnglish: 'At-Taghabun', ayahCount: 18, revelationType: 'Madani' },
  { number: 65, nameArabic: 'الطلاق', nameEnglish: 'At-Talaq', ayahCount: 12, revelationType: 'Madani' },
  { number: 66, nameArabic: 'التحريم', nameEnglish: 'At-Tahrim', ayahCount: 12, revelationType: 'Madani' },
  { number: 67, nameArabic: 'الملك', nameEnglish: 'Al-Mulk', ayahCount: 30, revelationType: 'Makki' },
  { number: 68, nameArabic: 'القلم', nameEnglish: 'Al-Qalam', ayahCount: 52, revelationType: 'Makki' },
  { number: 69, nameArabic: 'الحاقة', nameEnglish: 'Al-Haqqah', ayahCount: 52, revelationType: 'Makki' },
  { number: 70, nameArabic: 'المعارج', nameEnglish: 'Al-Maarij', ayahCount: 44, revelationType: 'Makki' },
  { number: 71, nameArabic: 'نوح', nameEnglish: 'Nuh', ayahCount: 28, revelationType: 'Makki' },
  { number: 72, nameArabic: 'الجن', nameEnglish: 'Al-Jinn', ayahCount: 28, revelationType: 'Makki' },
  { number: 73, nameArabic: 'المزمل', nameEnglish: 'Al-Muzzammil', ayahCount: 20, revelationType: 'Makki' },
  { number: 74, nameArabic: 'المدثر', nameEnglish: 'Al-Muddathir', ayahCount: 56, revelationType: 'Makki' },
  { number: 75, nameArabic: 'القيامة', nameEnglish: 'Al-Qiyamah', ayahCount: 40, revelationType: 'Makki' },
  { number: 76, nameArabic: 'الإنسان', nameEnglish: 'Al-Insan', ayahCount: 31, revelationType: 'Madani' },
  { number: 77, nameArabic: 'المرسلات', nameEnglish: 'Al-Mursalat', ayahCount: 50, revelationType: 'Makki' },
  { number: 78, nameArabic: 'النبأ', nameEnglish: 'An-Naba', ayahCount: 40, revelationType: 'Makki' },
  { number: 79, nameArabic: 'النازعات', nameEnglish: 'An-Naziat', ayahCount: 46, revelationType: 'Makki' },
  { number: 80, nameArabic: 'عبس', nameEnglish: 'Abasa', ayahCount: 42, revelationType: 'Makki' },
  { number: 81, nameArabic: 'التكوير', nameEnglish: 'At-Takwir', ayahCount: 29, revelationType: 'Makki' },
  { number: 82, nameArabic: 'الانفطار', nameEnglish: 'Al-Infitar', ayahCount: 19, revelationType: 'Makki' },
  { number: 83, nameArabic: 'المطففين', nameEnglish: 'Al-Mutaffifin', ayahCount: 36, revelationType: 'Makki' },
  { number: 84, nameArabic: 'الانشقاق', nameEnglish: 'Al-Inshiqaq', ayahCount: 25, revelationType: 'Makki' },
  { number: 85, nameArabic: 'البروج', nameEnglish: 'Al-Buruj', ayahCount: 22, revelationType: 'Makki' },
  { number: 86, nameArabic: 'الطارق', nameEnglish: 'At-Tariq', ayahCount: 17, revelationType: 'Makki' },
  { number: 87, nameArabic: 'الأعلى', nameEnglish: 'Al-Ala', ayahCount: 19, revelationType: 'Makki' },
  { number: 88, nameArabic: 'الغاشية', nameEnglish: 'Al-Ghashiyah', ayahCount: 26, revelationType: 'Makki' },
  { number: 89, nameArabic: 'الفجر', nameEnglish: 'Al-Fajr', ayahCount: 30, revelationType: 'Makki' },
  { number: 90, nameArabic: 'البلد', nameEnglish: 'Al-Balad', ayahCount: 20, revelationType: 'Makki' },
  { number: 91, nameArabic: 'الشمس', nameEnglish: 'Ash-Shams', ayahCount: 15, revelationType: 'Makki' },
  { number: 92, nameArabic: 'الليل', nameEnglish: 'Al-Lail', ayahCount: 21, revelationType: 'Makki' },
  { number: 93, nameArabic: 'الضحى', nameEnglish: 'Ad-Duha', ayahCount: 11, revelationType: 'Makki' },
  { number: 94, nameArabic: 'الشرح', nameEnglish: 'Ash-Sharh', ayahCount: 8, revelationType: 'Makki' },
  { number: 95, nameArabic: 'التين', nameEnglish: 'At-Tin', ayahCount: 8, revelationType: 'Makki' },
  { number: 96, nameArabic: 'العلق', nameEnglish: 'Al-Alaq', ayahCount: 19, revelationType: 'Makki' },
  { number: 97, nameArabic: 'القدر', nameEnglish: 'Al-Qadr', ayahCount: 5, revelationType: 'Makki' },
  { number: 98, nameArabic: 'البينة', nameEnglish: 'Al-Bayyinah', ayahCount: 8, revelationType: 'Madani' },
  { number: 99, nameArabic: 'الزلزلة', nameEnglish: 'Az-Zalzalah', ayahCount: 8, revelationType: 'Madani' },
  { number: 100, nameArabic: 'العاديات', nameEnglish: 'Al-Adiyat', ayahCount: 11, revelationType: 'Makki' },
  { number: 101, nameArabic: 'القارعة', nameEnglish: 'Al-Qariah', ayahCount: 11, revelationType: 'Makki' },
  { number: 102, nameArabic: 'التكاثر', nameEnglish: 'At-Takathur', ayahCount: 8, revelationType: 'Makki' },
  { number: 103, nameArabic: 'العصر', nameEnglish: 'Al-Asr', ayahCount: 3, revelationType: 'Makki' },
  { number: 104, nameArabic: 'الهمزة', nameEnglish: 'Al-Humazah', ayahCount: 9, revelationType: 'Makki' },
  { number: 105, nameArabic: 'الفيل', nameEnglish: 'Al-Fil', ayahCount: 5, revelationType: 'Makki' },
  { number: 106, nameArabic: 'قريش', nameEnglish: 'Quraysh', ayahCount: 4, revelationType: 'Makki' },
  { number: 107, nameArabic: 'الماعون', nameEnglish: 'Al-Maun', ayahCount: 7, revelationType: 'Makki' },
  { number: 108, nameArabic: 'الكوثر', nameEnglish: 'Al-Kawthar', ayahCount: 3, revelationType: 'Makki' },
  { number: 109, nameArabic: 'الكافرون', nameEnglish: 'Al-Kafirun', ayahCount: 6, revelationType: 'Makki' },
  { number: 110, nameArabic: 'النصر', nameEnglish: 'An-Nasr', ayahCount: 3, revelationType: 'Madani' },
  { number: 111, nameArabic: 'المسد', nameEnglish: 'Al-Masad', ayahCount: 5, revelationType: 'Makki' },
  { number: 112, nameArabic: 'الإخلاص', nameEnglish: 'Al-Ikhlas', ayahCount: 4, revelationType: 'Makki' },
  { number: 113, nameArabic: 'الفلق', nameEnglish: 'Al-Falaq', ayahCount: 5, revelationType: 'Makki' },
  { number: 114, nameArabic: 'الناس', nameEnglish: 'An-Nas', ayahCount: 6, revelationType: 'Makki' },
];
